apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp6
spec:
  selector:
    matchLabels:
      app: aspnetapp6
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetapp6
    spec:
      containers:
      - name: aspnetapp6
        image: bharatht08/apsnetapp6:v7
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp6-service
spec:
  type: LoadBalancer
  selector:
    app: aspnetapp6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 


